In [1]:
# Langchain Embedding API

# 라이브러리 불러오기
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings( 
    model="text-embedding-qwen3-embedding-8b",
    base_url="http://...:.../v1",
    api_key="lm-studio",
    check_embedding_ctx_length=False,
)

query_result = embeddings.embed_query('저는 배가 고파요')
print(query_result)

[0.017648400738835335, 0.009287641383707523, -0.0023873329628258944, -0.04438294097781181, 0.014782784506678581, -0.008044143207371235, -0.013311907649040222, -0.0056120045483112335, -0.00044960473314858973, 0.015197430737316608, -0.015585342422127724, -0.002215705346316099, 0.07027337700128555, -0.02565133199095726, 0.023162251338362694, 0.02400273084640503, 0.008959474042057991, -0.011576864868402481, 0.04650207236409187, 0.021422000601887703, 0.007223639637231827, 0.025404851883649826, 0.024856124073266983, -0.000676970521453768, 0.016197189688682556, 0.02231478877365589, -0.035327665507793427, 0.006801317445933819, -0.020232882350683212, 0.0413970947265625, -0.010402610525488853, -0.02367299795150757, -0.00781321246176958, 0.018650604411959648, -0.032230935990810394, 0.0017340087797492743, -0.027715714648365974, -0.009205734357237816, -0.004504940006881952, -0.008187657222151756, -0.01522859837859869, 0.010195701383054256, -0.0014211746165528893, 0.011135452426970005, -0.020732203498482704, -0.02925001084804535, -0.0033710142597556114, -0.00457216240465641, 0.02783340960741043, 0.02141737751662731, 0.012002602219581604, -0.01015517022460699, -0.02488766610622406, -0.0075066122226417065, -0.010511208325624466, -0.004330177791416645, -0.010173401795327663, -0.023406116291880608, -0.02681221067905426, -0.005141144152730703, -0.05634763464331627, 0.021512001752853394, 0.016062673181295395, -0.0182175375521183, 0.015493008308112621, 0.006324996240437031, 0.017647402361035347, -0.02992566116154194, 0.009784855879843235, 0.0006820348789915442, -0.0017490462632849813, 0.006504414137452841, -0.006665642373263836, -0.0006176093593239784, -0.00999625213444233, 0.027583511546254158, -0.03093954734504223, -0.030321408063173294, 0.005391738843172789, 0.031357213854789734, 0.008907410316169262, 0.01471779216080904, -0.016129406169056892, -0.04369667172431946, -0.003016598289832473, -0.031157325953245163, 0.008746538311243057, -0.01451638899743557, 0.0032823968213051558, 0.009040448814630508, 0.0037482341285794973, -0.0028914723079651594, 0.010149952955543995, 0.004539423622190952, -0.005846408195793629, -0.008618221618235111, -0.004861793015152216, -0.00570397125557065, -0.02183673530817032, -0.005581071134656668, 0.007429821416735649, 0.030353888869285583, -0.010279937647283077, -0.00020155543461441994, 0.014429021626710892, -0.0035601595882326365, -0.013966393657028675, 0.002865859540179372, -0.006610974203795195, -0.019182082265615463, 0.019402435049414635, 0.008550980128347874, 0.04131263121962547, 0.024968566372990608, -0.013016195967793465, -0.03353213146328926, -0.011532219126820564, 0.004035352263599634, 0.01325477845966816, 0.0021056768018752337, -0.0037801656872034073, -0.00034375989343971014, -0.00555889867246151, -0.02064500004053116, 0.005865318235009909, -0.0340815931558609, -0.007911955006420612, -0.006329960189759731, 0.015440987423062325, -0.018298586830496788, 0.0041272141970694065, -0.020289022475481033, -0.004015234299004078, -0.010380474850535393, 0.005109335295855999, 0.010507195256650448, -0.003648614278063178, -0.010501334443688393, -0.014616685919463634, 0.028707023710012436, -0.010360955260694027, 0.01749078556895256, 0.01959667168557644, -0.006766791455447674, 0.001644271076656878, 0.017280062660574913, -0.015871291980147362, -0.000999494339339435, 0.005712274927645922, 0.013354412280023098, -0.008956434205174446, 0.00020897234207950532, 0.004280109889805317, -0.026754045858979225, -0.008223408833146095, 0.0026212625671178102, -0.02727324143052101, 0.01798192225396633, 0.04208982735872269, 7.120036752894521e-05, 0.015543744899332523, 0.0014767490793019533, 0.010000556707382202, -0.010854704305529594, 0.0010879660258069634, -0.002128761727362871, 0.01343440730124712, -0.00666112219914794, 0.02037103660404682, 0.035157352685928345, 0.027269229292869568, -0.001628079335205257, -0.0359235480427742, 0.011987023055553436, -0.0066638849675655365, -0.026404814794659615, -0.033343639224767685, -0.013331431895494461, 0.012984814122319221, 0.015688322484493256, -0.006906505674123764, 0.008722742088139057, 0.0009221988148055971, 0.03228793665766716, 0.0010020609479397535, 0.022091424092650414, -0.008393107913434505, 0.004201371688395739, -0.009015090763568878, 0.009666107594966888, 0.004177562892436981, 0.005107058212161064, 0.0003168753464706242, 0.0010117404162883759, -0.0001837798918131739, 0.0006191721186041832, 0.0009133252315223217, 0.017548102885484695, -0.0026309990789741278, -0.00787150114774704, 0.05546991154551506, -0.02963973768055439, 0.003223660634830594, -0.0030191950500011444, -0.007057498674839735, 0.002051488496363163, -0.018104365095496178, 0.006736014038324356, 0.00572252320125699, -0.027882762253284454, 0.00031915941508486867, 0.0063543375581502914, 0.025979869067668915, 0.01862422004342079, -0.009166961535811424, 0.02467653714120388, 0.018733713775873184, -0.0016250447370111942, -0.01560321543365717, -0.0009075599955394864, 0.02517845667898655, -0.014458210207521915, 0.0037621648516505957, 0.008358661085367203, -0.02048243023455143, -0.04422761872410774, 0.016154630109667778, -0.0038724159821867943, -0.0068706911988556385, -0.02708972617983818, 0.01782095991075039, -0.015666572377085686, -0.0030068387277424335, -0.011499179527163506, -0.018460804596543312, -0.019741622731089592, 0.005164009053260088, -0.013390249572694302, -0.011032692156732082, 0.03876973316073418, -0.004869081545621157, 0.008977002464234829, -0.007999787107110023, 0.006457644514739513, -0.0010641112457960844, -0.004263519309461117, 0.010819795541465282, -0.028275715187191963, 0.013609575107693672, -0.03922666981816292, -0.00104745093267411, 0.008821691386401653, -0.006210387218743563, -0.011021172627806664, -0.02225484885275364, 0.004642884247004986, -0.0023549620527774096, -0.00949865859001875, -0.006938857492059469, 0.017582593485713005, 0.0008191547240130603, -0.02491467446088791, 0.011331789195537567, 0.023992527276277542, -0.016924377530813217, 0.007131451275199652, -0.014890164136886597, -0.027016345411539078, 0.013922044076025486, -0.003580246353521943, -0.002853742800652981, -0.024797046557068825, -0.014601221308112144, 0.005154833663254976, 0.005788889713585377, 0.030766122043132782, -0.00858028419315815, 0.001293701701797545, -0.020737165585160255, 9.644243255024776e-05, 0.0074403900653123856, -0.028754720464348793, 0.024401923641562462, -0.0360540896654129, 0.014225331135094166, -0.007242194842547178, -0.015164041891694069, 0.037544310092926025, -0.0014259706949815154, 0.012998574413359165, 0.01757088303565979, 0.015190058387815952, 0.0033082913141697645, 0.03226728364825249, -8.034191705519333e-05, -0.02149801328778267, -0.0198790542781353, -0.013717859983444214, 0.0015196530148386955, -0.006170274689793587, -0.005439974367618561, 0.0016522568184882402, 0.004843485075980425, -0.011409244500100613, -0.0024598108138889074, -0.006894014310091734, -0.02040420100092888, 0.009789838455617428, -0.00762032438069582, 0.0035514021292328835, -0.020427033305168152, -0.00971649494022131, -0.0019012127304449677, -0.009049770422279835, -0.030132073909044266, 0.010883917100727558, 0.009078862145543098, 0.02216688171029091, 0.005376522894948721, 0.012937051244080067, -0.012911581434309483, -4.123042458559212e-07, -0.01338822953402996, -0.026421694085001945, -0.0012418857077136636, -0.0026575885713100433, -0.003861174685880542, -0.010841503739356995, -0.01125575602054596, -0.013342144899070263, -0.020282531157135963, -0.021831141784787178, -0.004800803493708372, -0.003654249245300889, -0.015392856672406197, -0.0035221013240516186, 0.02831660583615303, -0.022592714056372643, 0.022551771253347397, -0.0025646481662988663, -0.013200429268181324, -0.030495867133140564, 0.01924510858952999, 0.0030596000142395496, 0.007321593817323446, 0.01605464145541191, 0.024688158184289932, -0.010104207322001457, -0.010686603374779224, -0.016307994723320007, -0.013906574808061123, -0.003025916637852788, 0.006960212718695402, 0.027983708307147026, 0.0016470192931592464, 0.007823417894542217, -0.012102900072932243, 0.030447348952293396, 0.02593124285340309, 0.0014806994004175067, 0.004683845676481724, 0.012205235660076141, 0.008302920497953892, -0.01851026713848114, 0.012538991868495941, 0.0010088837007060647, 0.01802142709493637, 0.012952669523656368, -0.030056774616241455, 0.002682338934391737, 0.013726486824452877, -0.0036053378134965897, -0.01973070204257965, -0.011063935235142708, -0.02139461226761341, 0.0011346935061737895, -0.000846169306896627, -0.014559563249349594, 0.018387066200375557, -0.00674970680847764, -0.010782335884869099, -0.04588339477777481, 0.005046950653195381, -0.015571211464703083, -0.0050159660167992115, 0.0047585079446434975, -0.01275500375777483, -0.01081860437989235, 0.012302592396736145, -0.0010744791943579912, -0.01414495985955, -0.004762045573443174, -0.001856363844126463, -0.0038019982166588306, -0.007428140379488468, 0.0026597839314490557, 0.0026217971462756395, -0.015485730953514576, -0.006302404683083296, 0.02120504528284073, 0.035899173468351364, -0.022243903949856758, -0.0044799852184951305, 0.02498352713882923, -0.014605122618377209, -0.0014427112182602286, -0.015834003686904907, 0.0008522559073753655, -0.002930356888100505, 0.005734466016292572, -0.020879417657852173, -0.0029428547713905573, 0.017730455845594406, 0.004176000133156776, -0.01235725823789835, 0.012148250825703144, 0.010936284437775612, 0.04132718965411186, 0.0007439121254719794, -0.03390686586499214, -0.02648010663688183, 0.019878380000591278, 0.008690353482961655, 0.0033188252709805965, -0.009448034688830376, 0.015504326671361923, 0.010088509880006313, -0.006468386389315128, 0.00014386513794306666, -0.00817610789090395, -0.0028759450651705265, -0.007583475671708584, -0.044880449771881104, 0.009730871766805649, -0.0025896248407661915, 0.014064773917198181, 0.03480702266097069, 0.0015957436989992857, 0.010284320451319218, 0.010645562782883644, 0.0031548028346151114, -0.005133611150085926, -0.004411892034113407, 0.021518198773264885, -0.0032771548721939325, 0.015399836003780365, -0.00525238923728466, 0.001582068158313632, 0.00011633866961346939, -0.017482899129390717, -0.00430654501542449, 0.022773418575525284, -0.007716238033026457, -0.0105010736733675, -0.022268783301115036, -0.014622111804783344, -0.012219522148370743, -0.006971187889575958, -0.010347019881010056, 0.012346823699772358, 0.01901174895465374, -0.018856624141335487, -0.006703369785100222, -0.01740671508014202, 0.006755542941391468, -0.026225518435239792, 0.014491956681013107, -0.006822563707828522, -0.0224264245480299, -0.008735062554478645, -0.04121082276105881, 0.009876270778477192, -0.020077930763363838, -0.017016474157571793, -0.017836404964327812, 0.037700921297073364, 0.012393745593726635, -0.004702601116150618, 0.002835588762536645, -0.01352749764919281, -0.013594496063888073, -0.024961570277810097, -0.011445704847574234, -0.02748638391494751, 0.027410872280597687, 0.055770885199308395, 0.013818970881402493, -0.03024352341890335, -0.01808878593146801, 0.0025615852791815996, -0.02337144874036312, 0.005564719904214144, 0.001280709053389728, -0.021030085161328316, 0.024961179122328758, 0.007879645563662052, 0.011901172809302807, -0.012678542174398899, 0.03215595334768295, -0.016146143898367882, 0.0056340014562010765, -0.014072847552597523, 0.001182491541840136, -0.012070344761013985, -0.009178468026220798, 0.0011169582139700651, 0.03360971435904503, -0.0012562109623104334, 0.02432696893811226, 0.013385412283241749, 0.020804960280656815, -0.01742469146847725, -0.013350212015211582, 0.005625324789434671, -0.01107810903340578, -0.020083235576748848, 0.007148767355829477, -0.011383086442947388, -0.003654444357380271, 0.02723187580704689, 0.014172877185046673, 0.005882361438125372, -0.01749248430132866, -0.015826599672436714, 0.016813671216368675, -0.0015666978433728218, -0.006513029802590609, -0.001618066569790244, -0.008007378317415714, -0.02242031879723072, -0.03283242881298065, 0.013474381528794765, -0.028356092050671577, 0.005275513976812363, -0.008174723945558071, -0.018100673332810402, 0.01377552654594183, 0.002197572262957692, 0.012702918611466885, -0.010582877323031425, -0.002213721862062812, 0.020009322091937065, 0.0034182961098849773, -0.022654229775071144, -0.011573144234716892, 0.02317081205546856, -0.008654109202325344, -0.021731602028012276, 0.015483049675822258, 0.029441406950354576, -0.0036277594044804573, 0.025249842554330826, 0.011267835274338722, -0.0030741330701857805, 0.00021979858865961432, 0.022155776619911194, -0.01834327168762684, 0.007267912849783897, -0.014414793811738491, 0.008181417360901833, 0.004687201231718063, 0.00632886029779911, -0.008395052514970303, -0.01446242444217205, -0.01855272613465786, -0.017077740281820297, -0.004726619925349951, 0.011676480993628502, -0.016006337478756905, 0.01442345604300499, -0.013172918930649757, -0.011972611770033836, 0.01810586452484131, 0.010680994018912315, 0.006978496443480253, 0.014184793457388878, -0.023507386445999146, 0.014464220963418484, 0.0382959246635437, -0.007559147663414478, 0.011248582974076271, 0.003335963934659958, 0.014942077919840813, 0.005305434111505747, 0.004464524332433939, -0.023811019957065582, 0.0029202490113675594, -0.016711324453353882, -0.004104997962713242, -0.018161432817578316, 0.0026740923058241606, -0.006244397256523371, 0.00625099940225482, -0.02411455474793911, -0.005344098899513483, 0.007052058819681406, -0.0012450470821931958, -0.024351663887500763, 0.003261522389948368, -0.005055550951510668, 0.0011953646317124367, -0.0027766760904341936, 0.00926408264786005, 0.01627170667052269, 0.00547451339662075, 0.02995396964251995, 0.0017249234952032566, -0.005672823172062635, 0.0028751667123287916, -0.015841221436858177, 0.004923657048493624, 0.014280404895544052, -0.013001933693885803, 0.0044503300450742245, -0.006070671137422323, -0.016153061762452126, 0.004882413893938065, -0.016652805730700493, 0.0015709542203694582, 0.023322105407714844, -0.008775069378316402, -0.01849144883453846, 0.0010253164218738675, 0.00036307726986706257, 0.005945564713329077, 0.022486595436930656, 0.007909636944532394, -0.007421678397804499, -0.013535642065107822, 0.0028301153797656298, -0.009565163403749466, 0.00030441253329627216, -0.0011895595816895366, -0.012810301035642624, -0.02697771042585373, -0.0008037563529796898, 0.010614017955958843, 0.01045546866953373, -0.02836533822119236, 0.014377223327755928, 0.016087252646684647, -0.004016869235783815, 0.006257844623178244, 0.01861259527504444, 0.018105458468198776, -0.00039282525540329516, 0.008910631760954857, 0.013173209503293037, 0.0016310695791617036, 0.028350964188575745, 0.015197210945189, 0.0050496929325163364, 0.018473224714398384, 0.007288055960088968, 0.013298300094902515, -0.02303421124815941, 0.009416074492037296, -0.0012760671088472009, -0.0142145324498415, -0.0231889970600605, -0.01735597476363182, -0.003502120263874531, -0.021709442138671875, -0.019276021048426628, -0.0020973028149455786, 0.009155774489045143, 0.0009675208129920065, 0.01848735101521015, 0.020585305988788605, -0.011530661024153233, -0.03516490384936333, 0.009226101450622082, 0.0006500032031908631, 0.015856711193919182, 0.015287220478057861, -0.007573544979095459, 0.037932660430669785, 0.026827717199921608, 0.003589784959331155, -0.016148259863257408, -0.006193388719111681, -0.018787257373332977, -0.03305647522211075, 0.008513973094522953, 0.008157089352607727, -0.020884543657302856, -0.008114708587527275, 0.0033405551221221685, 0.020718218758702278, 0.007920811884105206, 0.015383128076791763, -0.02306319959461689, 0.004575809463858604, -0.012055439874529839, 0.005264444276690483, 0.019223079085350037, -0.00796997919678688, -0.025033660233020782, 0.013176854699850082, 0.00046905784984119236, -0.0027072117663919926, -0.010314208455383778, -0.025910139083862305, -0.029620923101902008, -0.011536174453794956, -0.014304639771580696, -0.027029825374484062, 0.00764926103875041, -0.0012878485722467303, -0.008173054084181786, -0.0017256058054044843, 0.013870407827198505, 0.0007197196246124804, 0.013153928332030773, 0.006035455036908388, -0.03246137127280235, 0.005419077817350626, -0.004497189540416002, 0.0020289928652346134, -0.02716892771422863, -0.013032117858529091, -0.006130577530711889, -0.0011245593195781112, 0.007275586947798729, -0.00933142751455307, -0.03524109348654747, -0.0033541282173246145, 0.016205396503210068, 0.003188906004652381, -0.03798097372055054, 0.0029308076482266188, 0.00420969957485795, -0.0036640784237533808, 0.003396634478121996, -0.021730056032538414, -0.01154002919793129, -0.0013760047731921077, -0.01070619560778141, -0.003775452496483922, -0.016827479004859924, -0.02413039095699787, -0.023668797686696053, -0.0014232981484383345, 0.010088962502777576, -0.003952373750507832, 0.00652757054194808, 0.0025740854907780886, -0.014771871268749237, 0.00796856265515089, -0.01728210598230362, 0.0026717868167907, 0.007131985388696194, 0.00803503580391407, -0.0025803735479712486, 0.013270962983369827, 0.003988898824900389, -0.03902342915534973, 0.0013220561668276787, 0.02313631772994995, 0.00984802283346653, -0.014797606505453587, 0.01303503755480051, -0.02281624637544155, 0.025004995986819267, 0.018441157415509224, -0.012055454775691032, -0.002906781155616045, 0.016498379409313202, 0.021310944110155106, -0.007993404753506184, 0.011347395367920399, -0.0004120503435842693, -0.00243620784021914, 0.010903800837695599, -0.012672360986471176, -0.025347981601953506, -0.00774883758276701, 0.016844579949975014, 0.0021630951669067144, 0.013899220153689384, -0.010160453617572784, 0.02209966629743576, 0.020348621532320976, -0.0019092974252998829, 0.008140954189002514, 0.015543539077043533, -0.014835926704108715, 0.031594134867191315, 0.008687705732882023, 0.01314027700573206, -0.026767002418637276, -0.005155941005796194, 0.03821370750665665, 0.006838975474238396, 0.02293700911104679, -0.005197566468268633, 0.0005750279524363577, 0.0005377174238674343, 0.008461952209472656, 0.012609997764229774, -0.004566167015582323, 0.014864807017147541, 0.0018543775659054518, 0.013408715836703777, -0.0030881394632160664, 0.008219883777201176, -0.008869069628417492, -0.006285562179982662, 0.0014299582690000534, 0.008615484461188316, 0.008329560048878193, 0.04717621952295303, 0.004835004452615976, -0.0071945590898394585, 0.007067943457514048, 0.01311702374368906, -0.01496895868331194, -0.015621108934283257, -0.023665452376008034, 0.0002651524846442044, 0.0134095074608922, -0.017217271029949188, 0.028919344767928123, 0.03866468369960785, -0.014468111097812653, 0.0008812972228042781, 0.010235399939119816, 0.0059166112914681435, 0.010649076662957668, -0.006947216112166643, 0.0015504221664741635, -0.0008678440353833139, -0.003988472279161215, 0.006033378653228283, -0.017441583797335625, -0.009388209320604801, -0.009023929946124554, -0.0023471475578844547, 0.02220962569117546, 0.002340909093618393, 0.002447702456265688, -0.020252088084816933, -0.013494673185050488, -0.014445486478507519, 0.013947690837085247, 0.011257973499596119, -0.004736981354653835, 0.020172609016299248, -0.0033970645163208246, 0.003480491228401661, -0.004461976699531078, -0.008648732677102089, 0.013461004942655563, -0.00742793595418334, -0.014958271756768227, 0.005098700989037752, -0.004860876128077507, 0.0028891395777463913, 0.0033627271186560392, 0.013679750263690948, 0.004138350952416658, -0.01990215852856636, 0.01747415028512478, -0.001734221470542252, -0.008588090538978577, -0.017953043803572655, 0.0013654556823894382, -0.021321097388863564, -0.017463432624936104, -0.0009900749428197742, 0.0013055027229711413, 0.004122127778828144, -0.00870881974697113, -0.009696530178189278, 0.01489950716495514, -0.018975388258695602, -0.015740489587187767, 0.016255106776952744, -0.0013989394064992666, -0.04070581868290901, -0.01746426895260811, 0.005086824297904968, -0.004768539220094681, 0.0006023580790497363, -0.014433294534683228, 0.00451806141063571, -0.011931613087654114, 0.0021236950997263193, 0.003922280855476856, 0.007690909318625

In [2]:
data = [
    '주식 시장이 급등했어요',
    '시장 물가가 올랐어요',
    '전통 시장에는 다양한 물품들을 팔아요',
    '부동산 시장이 점점 더 복잡해지고 있어요',
    '저는 빠른 비트를 좋아해요',
    '최근 비트코인 가격이 많이 변동했어요'
]

df = pd.DataFrame(data, columns=['text'])

df

                     text
0            주식 시장이 급등했어요
1             시장 물가가 올랐어요
2    전통 시장에는 다양한 물품들을 팔아요
3  부동산 시장이 점점 더 복잡해지고 있어요
4          저는 빠른 비트를 좋아해요
5    최근 비트코인 가격이 많이 변동했어요

In [3]:
# 텍스트 임베딩 벡터로 변환하는 함수 정의
def get_embedding(text):
    return embeddings.embed_query(text)

# DataFrame의 각 행에 대해 'text' 열의 내용을 임베딩 벡터로 변환
df['embedding'] = df.apply(
    lambda row: get_embedding(row.text),
    axis=1
)

# 변환된 DataFrame 출력
df

                     text                                          embedding
0            주식 시장이 급등했어요  [0.003425918985158205, 0.012388941831886768, -...
1             시장 물가가 올랐어요  [0.0124553507193923, 0.023535393178462982, -0....
2    전통 시장에는 다양한 물품들을 팔아요  [-0.01394876092672348, 0.023344269022345543, -...
3  부동산 시장이 점점 더 복잡해지고 있어요  [0.009744472801685333, 0.014037452638149261, -...
4          저는 빠른 비트를 좋아해요  [0.031136970967054367, 0.002553999423980713, 0...
5    최근 비트코인 가격이 많이 변동했어요  [0.024296490475535393, 0.022296005859971046, 0...

In [4]:
# 코사인 유사도 계산 함수
def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

# 주어진 쿼리와 가장 유사한 상위 3개의 문서를 반환하는 함수
def return_answer_candidate(df, query):
    # 쿼리 텍스트를 임베딩 벡터로 변환
    query_embedding = get_embedding(query)

    # DataFrame의 각 문서 임베딩과 쿼리 임베딩 간의 유사도 계산
    df["similarity"] = df.embedding.apply(lambda x: cos_sim(np.array(x), np.array(query_embedding)))

    # 유사도가 높은 순으로 정렬하고 상위 3개 문서 선택
    top_three_doc = df.sort_values("similarity", ascending=False).head(3)

    return top_three_doc

# 예시 쿼리로 유사한 문서 검색
sim_result = return_answer_candidate(df, '과일 값이 비싸다')
sim_result

,text,embedding,similarity
1,시장 물가가 올랐어요,"[0.0124553507193923, 0.023535393178462982, -0....",0.700582
5,최근 비트코인 가격이 많이 변동했어요,"[0.024296490475535393, 0.022296005859971046, 0...",0.584192
0,주식 시장이 급등했어요,"[0.003425918985158205, 0.012388941831886768, -...",0.580358

In [6]:
# 다른 모델로 테스트
embeddings = OpenAIEmbeddings( 
    model="text-embedding-nomic-embed-text-v1.5",
    base_url="http://...:.../v1",
    api_key="lm-studio",
    check_embedding_ctx_length=False,
)

# DataFrame의 각 행에 대해 'text' 열의 내용을 임베딩 벡터로 변환
df['embedding'] = df.apply(
    lambda row: get_embedding(row.text),
    axis=1
)

# 예시 쿼리로 유사한 문서 검색
sim_result = return_answer_candidate(df, '과일 값이 비싸다')
sim_result

,text,embedding,similarity
5,최근 비트코인 가격이 많이 변동했어요,"[-0.03933055326342583, -0.00351810734719038, -...",0.816629
3,부동산 시장이 점점 더 복잡해지고 있어요,"[-0.0006923280889168382, 0.012346523813903332,...",0.785077
0,주식 시장이 급등했어요,"[-0.00934308860450983, -0.00351078063249588, -...",0.761756